### ISSUE TITLE
Problem with registering namespaced classes and logging errors

### ISSUE THREAD

**Issue by msrumon** [daveh/php-mvc#49]
I am having trouble finding where the problem is:
**Folder structure:**
```
_PUBLIC_
|-- Controllers
    |-- Home.php
|-- Views
    |-- index.php
MSR
|-- Controller.php
|-- Errors.php
|-- Router.php
|-- View.php
public_html
|-- .htaccess
|-- index.php
```

**Inside `MSR/Controller.php`:**
```php
<?php

/**
  * Custom MVC design pattern
  * @author MS RUMON
  * @version PHP v7
  */

namespace MSR;

abstract class Controller
{
  /**
    * JSON object to hold all my info
    *
    * @var object
    */
  protected static $json;

  /**
    * Parameters from matched route
    *
    * @var array
    */
  protected static $route_params = [];

  /**
    * Class Constructor: Assigns values into properties
    *
    * @param array $params -> Route parameters to store $route_params
    *
    * @return void
    */
  function __construct (array $params)
  {
    // self::$json = file_get_contents(__DIR__ . "/../assets/all.json");
    self::$route_params = $params;
  }
}
```

**Inside `MSR/Errors.php`:**
```php
<?php

/**
  * Custom MVC design pattern
  * @author MS RUMON
  * @version PHP v7
  */

namespace MSR;

class Errors
{
  /**
    * Defines whether or not errors are shown in details
    *
    * @var bool
    */
  private static $errors = true;

  /**
    * Converts all errors into exceptions
    *
    * @param int $level -> The level/severity of error
    * @param string $message -> Error message to display
    * @param string $file -> Name of the file which raised the error
    * @param int $line -> Number of line where the error occured in that file
    *
    * @return void
    */
  public static function errors_exceptions (int $level, string $message, string $file, int $line) : void
  {
    if(error_reporting() !== 0) throw new \ErrorException($message, 0, $level, $file, $line);
  }

  /**
    * Handles exceptions
    *
    * @param Exception $exception -> The exception
    *
    * @return void
    */
  public static function handle_exceptions ($exception) : void
  {
    /**
      * Building up the $message for logging
      */
    $message = "\nUncaught (" . get_class($exception) . "): \"" . $exception->getMessage() .  "\"";
    $message .= "\n\nStack Trace:\n";

    $message .= $exception->getTraceAsString();

    $message .= "\n\nThrown at line " . $exception->getLine() . " in \"" . $exception->getFile() . "\" file.";

    /**
      * Sending appropriate status
      */
    http_response_code($exception->getCode());

    /**
      * Displaying error message for developers
      *
      * @uses self::$errors must be true
      */
    if(self::$errors) echo "<pre>{$message}</pre>";

    /**
      * Saving error message into separate log file and displaying error page for users
      *
      * @uses self::$errors must be false
      */
    else
    {
      $log = __DIR__ . "/../" . APP_NAME . "/_errors/" . date("Ymd-HisT") . ".log";
      ini_set("error_log", $log);
      error_log($message);

      /**
        * Rendering views for specific errors
        */
      View::error($exception->getCode());
    }
  }
}
```

**Inside `MSR/Router.php`:**
```php
<?php

/**
  * Custom MVC design pattern
  * @author MS RUMON
  * @version PHP v7
  */

namespace MSR;

abstract class Router
{
  /**
    * "Routing Table"
    *
    * @var array
    */
  private static $routes = [];

  /**
    * Route parameters (if any)
    *
    * @var array
    */
  private static $params = [];

  /**
    * Sets a route to the routing table
    *
    * @param string $route -> The route URL
    * @param array $params -> Parameters (controller, action etc.)
    *
    * @return void
    */
  public static function set (string $route, array $params = []) : void
  {
    $route = preg_replace("/\//", "\\/", $route);
    $route = preg_replace("/\{([a-z]+)\}/", "(?<\\1>[a-z-]+)", $route);
    $route = preg_replace("/\{([a-z]+):([^\}]+)\}/", "(?<\\1>\\2)", $route);
    $route = "/^{$route}$/i";
    self::$routes[$route] = $params;
  }

  /**
    * Gets all the routes from the routing table
    *
    * @return array
    */
  public static function get () : array
  {
    return self::$routes;
  }

  /**
    * Gets the list of parameters of current route
    *
    * @return array
    */
  public static function params () : array
  {
    return self::$params;
  }

  /**
    * Validates a route to the routes in the routing table
    * and sets the $params property if that route is found
    *
    * @param string $query_string -> The route URL
    *
    * @return bool TRUE if a match is found, FALSE otherwise
    */
  private static function validate (string $query_string) : bool
  {
    foreach(self::$routes as $route => $params)
    {
      if(preg_match($route, $query_string, $matches))
      {
        foreach($matches as $key => $mat) if(is_string($key)) $params[$key] = $mat;
        self::$params = $params;
        return true;
      }
    }
    return false;
  }

  /**
    * Dispatches the route, creates "controller" object and runs "action" methods
    *
    * @param string $query_string -> The route URL (received from $_SERVER["QUERY_STRING"])
    *
    * @return void
    */
  public static function dispatch (string $query_string) : void
  {
    $query_string = self::remove_query_string($query_string);

    if(self::validate($query_string))
    {
      $controller = self::$params["controller"];
      $controller = self::sTuDlYcApS($controller);
      $controller = self::name_space() . $controller;

      if(class_exists ($controller))
      {
        $controller_object = new $controller(self::$params);

        $action = self::$params["action"];
        $action = self::camelCase($action);

        // if(preg_match("/action$/i", $action) == 0) $controller_object->$action();
        if(is_callable([$controller_object, $action])) $controller_object->$action();
        else throw new \Exception("{$controller}::{$action}() is either NOT found or private/protected!", 500);
      }
      else throw new \Exception("Controller class {$controller} is either NOT found or NOT created yet!", 500);
    }
    else throw new \Exception("There is NOTHING specified for this particular route: /{$query_string}!", 404);
  }

  /**
    * Converts the controller class names to StUdLyCaPs
    *
    * @param string $string -> The string to convert
    *
    * @return string
    */
  private static function sTuDlYcApS (string $string) : string
  {
    $string = str_replace("-", " ", $string);
    $string = ucwords($string);
    $string = str_replace(" ", "", $string);
    return $string;
  }

  /**
    * Converts the action method names to camelCase
    *
    * @param string $string -> The string to convert
    *
    * @return string
    */
  private static function camelCase (string $string) : string
  {
    $string = self::sTuDlYcApS($string);
    $string = lcfirst($string);
    return $string;
  }

  /**
    * Removes the query string parameter from the URL (if any)
    * @param string $query_string -> The full URL
    *
    * @return string
    */
  private static function remove_query_string (string $query_string) : string
  {
    if ($query_string != "")
    {
      $parts = explode ("&", $query_string, 2);
      if (strpos ($parts[0], "=") === false) $query_string = $parts[0];
      else $query_string = "";
    }
    return $query_string;
  }

  /**
    * Gets the current namespace for the controller class
    *
    * @return $namespace -> The reuqest URL
    */
  private static function name_space () : string
  {
    $namespace = APP_NAME . "\Controllers\\";
    if(array_key_exists("namespace", self::$params)) $namespace .= self::$params["namespace"] . "\\";
    return $namespace;
  }
}
```

**Inside `MSR/View.php`:**
```php
<?php

/**
  * Custom MVC design pattern
  * @author MS RUMON
  * @version PHP v7
  */

namespace MSR;

abstract class View
{
  /**
    * Renders a view file
    * @param string $filename -> Name of view file
    * @param array $data -> Associative array of data to be passed into view (Optional)
    *
    * @return void
    */
  public static function render (string $filename, array $data = []) : void
  {
    extract($data, EXTR_SKIP);
    $file = __DIR__ . "/../" . APP_NAME . "/Views/{$filename}";
    if(is_readable($file)) require_once $file;
    else throw new \Exception("Couldn't render this view: {$file}!", 404);
  }

  /**
    * Displays error page
    *
    * @param int $code -> The response code passed from Errors class
    * @return void
    */
  public static function error (int $code) : void
  {
    $file = __DIR__ . "/../" . APP_NAME . "/_error_pages_/{$code}.php";
    if(is_readable($file)) require_once $file;
    else throw new \Exception("Couldn't render the associated error page: {$file}!", 1);
  }
}
```

**Inside `_PUBLIC_/Controllers/Home.php`:**
```php
<?php

namespace _PUBLIC_\Controllers;

use MSR\View;

class Home extends MSR\Controller
{
  public static function index () : void
  {
    View::render("index.php");
  }
}
```

**Inside `_PUBLIC_/Views/index.php`:**
```php
<?php

echo "hello world";
```

**Inside `public_html/.htaccess`:**
```
php_value date.timezone "Asia/Dhaka"

RewriteEngine On

#RewriteCond %{HTTPS} off
#RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

#RewriteCond %{HTTPS} on
#RewriteCond %{HTTP_HOST} !^www\. [NC]
#RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-l
RewriteRule ^(.*)$ index.php?$1 [L,QSA]
```

**Inside `public_html/index.php`:**
```php
<?php

/**
  * Front Controller of _PUBLIC_
  * @version PHP 7
  */
  
/**
  * Using required namespaces
  */
use MSR\Router;
use MSR\Request;

/**
  * Defining application name
  */
define("APP_NAME", "_PUBLIC_");
define("APP_DIR", "public_html");

/**
  * Autoloading classes
  */
spl_autoload_register(function($class)
{
  $file = __DIR__ . "/../" . str_replace("\\", "/", $class) . ".php";
  if(is_readable($file)) require_once $file;
  else throw new \Exception("Couldn't find this REQUIRED resource: {$file}!", 500);

});

/**
  * Defining error and exception handlers
  */
error_reporting(E_ALL);
set_error_handler("MSR\Errors::errors_exceptions");
set_exception_handler("MSR\Errors::handle_exceptions");

/**
  * Turning on session
  */
// session_start();

/**
  * Copying or modifying assets from sources
  */
// Request::asset("assets/favicon.ico", "assets");
// Request::asset("css/main.css", "styles");
// Request::asset("materialize-src/js/bin/materialize.js", "scripts", "main.js");
// Request::asset("Vendors/fontawesome/js/all.js", "scripts", "fa.js");
// Request::asset("assets/logo.svg", "assets");

/**
  * Setting routers
  */
Router::set("", ["controller" => "Home", "action" => "index"]);
Router::set("{action}", ["controller" => "Home"]);
Router::set("{controller}/{action}");

/**
  * Dispatching routers
  */
Router::dispatch($_SERVER["QUERY_STRING"]);
```

1. When I go to `/public_html`, I get the following error (shown by `Errors::handle_exceptions()`): (expected to see the rendered view from **`_PUBLIC_/Views/index.php`**)
```
Uncaught (Exception): "Couldn't find this REQUIRED resource: localhost/master/public_html/../_PUBLIC_/Controllers/MSR/Controller.php!"

Stack Trace:
#0 [internal function]: {closure}('_PUBLIC_\\Contro...')
#1 localhost/master/_PUBLIC_/Controllers/Home.php(7): spl_autoload_call('_PUBLIC_\\Contro...')
#2 localhost/master/public_html/index.php(26): require_once('localhost/master/...')
#3 [internal function]: {closure}('_PUBLIC_\\Contro...')
#4 [internal function]: spl_autoload_call('_PUBLIC_\\Contro...')
#5 localhost/master/MSR/Router.php(103): class_exists('_PUBLIC_\\Contro...')
#6 localhost/master/public_html/index.php(62): MSR\Router::dispatch('')
#7 {main}

Thrown at line 27 in "localhost/master/public_html/index.php" file.
```
2. When I set `$errors = false` in **`MSR/Errors.php`** for displaying error page to user and logging details in server, it doesn't write anything.

It would be helpful to me if someone helps me find these two bugs.
Thanks in advance.

**Comment by daveh** [comment]
It's a namespace problem. Your Home controller class is extending the MSR\Controller class, but as your Home class is in another namespace, you need to refer to the MSR\Controller class by prefixing it with a backslash (which refers to the root namespace) like this:

```
namespace _PUBLIC_\Controllers;

use MSR\View;

//class Home extends MSR\Controller
class Home extends \MSR\Controller
{
```

or import the MSR\Controller class into the current namespace with `use`, then you can just extend the Controller class without its namespace, like this:

```
namespace _PUBLIC_\Controllers;

use MSR\View;
use MSR\Controller;

//class Home extends MSR\Controller
class Home extends Controller
{
```

**Comment by msrumon** [comment]
Thank you. My problem is resolved now.
