### ISSUE TITLE
syntax error unexpected array in Router.php

### ISSUE THREAD

**Issue by pagodzik** [daveh/php-mvc#86]
I have this error with PHP Version 7.3.2. Works good with 7.4.4.

`Fatal error
Uncaught exception: 'ParseError'

Message: 'syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)'

Stack trace:

#0 C:\wamp\www\flexim-hotesse-virtuelle\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\wamp\\www\\fle...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\Router')
#2 C:\wamp\www\flexim-hotesse-virtuelle\public\index.php(33): spl_autoload_call('Core\\Router')
#3 {main}
Thrown in 'C:\wamp\www\flexim-hotesse-virtuelle\Core\Router.php' on line 20`

What is missing here?

**Comment by daveh** [comment]
It looks like an error with Composer - Composer requires PHP 7.4, so it won't work with 7.3.2.
